### ISSUE TITLE
TypeScript default exports disagree with source files

### ISSUE THREAD

**Issue by jtbandes** [gkjohnson/xacro-parser#54]
In TypeScript, I can't `import {XacroParser} from "xacro-parser"` because the type definitions are only in `src`, not `umd` (probably the same `"type": "module"` issue we discussed for `urdf-loader`).

On the other hand, I can `import XacroParser from "xacro-parser/src/XacroParser";` and TypeScript will understand that the default export is a class: https://github.com/gkjohnson/xacro-parser/blob/e03b7e401f6530c864e7f6026f121983d488e436/src/XacroParser.d.ts#L1
However, src/XacroParser.js doesn't actually have a default export, instead it has a named export: https://github.com/gkjohnson/xacro-parser/blob/e03b7e401f6530c864e7f6026f121983d488e436/src/XacroParser.js#L17

**Comment by gkjohnson** [comment]
Thanks! Should be fixed in #55. Can you take a look to make sure that's all that needs to be done?

**Comment by jtbandes** [comment]
Yep I think that's all that's needed!
