### ISSUE TITLE
wrong ts.d for XacroLoader

### ISSUE THREAD

**Issue by ajs124** [gkjohnson/xacro-parser#65]
According to [the ts.d](https://github.com/gkjohnson/xacro-parser/blob/master/src/XacroLoader.d.ts#L14) `.load` takes the parameters `url: string, onLoad: (xml: XMLDocument) => void, options?: XacroLoaderOptions`, but [the actual implementation](https://github.com/gkjohnson/xacro-parser/blob/master/src/XacroLoader.js#L13) (probably) takes a string and two functions, so the ts.d should probably say something like `load(url: string, onLoad: (xml: XMLDocument) => void, onError: (err: Error) => void): Promise<XMLDocument>` instead.

**Comment by gkjohnson** [comment]
Hello! Thanks for the catch -- looks like the js files got out of sync with the types. Do you want to create a PR to update the d.ts file? The README is up to date with the latest function signatures.
