### ISSUE TITLE
roll=0.0 param fails to parse

### ISSUE THREAD

**Issue by jhurliman** [gkjohnson/xacro-parser#72]
The following line:

```xml
<xacro:macro name="stack_bottom_pole" params="parent number x_loc y_loc z_loc roll=0.0 pitch=0.0 yaw=0.0">
```

from https://github.com/turtlebot/turtlebot/blob/melodic/turtlebot_description/urdf/stacks/hexagons.urdf.xacro#L13 fails to parse correctly. The `=0.0` is treated as part of the parameter name instead of a default value.

**Comment by gkjohnson** [comment]
Hello! Thanks for the report. From the [xacro documentation](http://wiki.ros.org/xacro#Default_parameters) it seemed to be that only the `:=` syntax was mentioned but looking at some of the official tests and your file it seems that `=` is valid, as well, and should behave the same. Would you like to make a PR with a fix? If I recall correctly it seems only [the parseMacroParam function](https://github.com/gkjohnson/xacro-parser/blob/master/src/XacroParser.js#L196) would have to change.

I think a full fix would include the following:
- Update the `parseMacroParam` function to support "=" default parameters.
- Add a test (or possibly just enable [this one](https://github.com/gkjohnson/xacro-parser/blob/master/test/XacroOfficial.test.js#L127-L143)) to test default macro params using `=`.
- Add a small section to the [Undocumented Xacro Behavior](https://github.com/gkjohnson/xacro-parser#undocumented-xacro-behavior) section describing that `:=` and `=` are the same for Macro default parameters.

Thanks again!

**Comment by jhurliman** [comment]
PR created at https://github.com/gkjohnson/xacro-parser/pull/73, thanks for the guidance!
