### ISSUE TITLE
Error importing XacroLoader in my typescript project

### ISSUE THREAD

**Issue by joaopfg** [gkjohnson/xacro-parser#77]
Hello,

When trying to `import { XacroLoader } from 'xacro-parser';` in my typescript project I'm getting the error:

```
Error: node_modules/xacro-parser/src/XacroParser.d.ts:3:75 - error TS7006: Parameter 'command' implicitly has an 'any' type.

3     rospackCommands?: { [key: string]: (...args:string[]) => string } | ((command, ...args: string[]) => string);
```

My typescript compiler options are:

```
"forceConsistentCasingInFileNames": true,
"strict": true,
"noImplicitReturns": true,
"noFallthroughCasesInSwitch": true,
"sourceMap": true,
"declaration": false,
"downlevelIteration": true,
"experimentalDecorators": true,
"moduleResolution": "node",
"importHelpers": true,
"target": "es2017",
"module": "es2020",
"lib": [
      "es2018",
      "dom"
]
```

**Comment by gkjohnson** [comment]
Thanks! Looks like I hadn't set up typescript linting on this project. Would you like to make a PR that adds typescript file validation to catch these kinds of errors and fix the above issue?

You can see the typescript command included in the lint script [here](https://github.com/gkjohnson/three-mesh-bvh/blob/master/package.json#L15) in the three-mesh-bvh package. And here's the [tsconfig file](https://github.com/gkjohnson/three-mesh-bvh/blob/master/tsconfig.json) used in that project which can be reused here.

**Comment by joaopfg** [comment]
Hello, @gkjohnson , I will try it

**Comment by gkjohnson** [comment]
The official `xacro` tool calls out to other ROS cli commands in order to work. Of course "rospack find ros_robotics" cli command is not available in the browser but you can implement it yourself using the "rospackCommands" option.

**Comment by joaopfg** [comment]
@gkjohnson Thanks for clarification. I thought this syntax `rospack find` would be interpreted by `xacro-parser` in a equivalent way it's interpreted on linux shell (doing a pattern mathing on the HTTP server filesystem for what `find` is looking for and loading the xml following the urdf grammar).

**Comment by gkjohnson** [comment]
> doing a pattern mathing on the HTTP server filesystem for what find is looking for

This isn't possible to do generally with static file servers but you can implement it this way yourself if you have control over the file service. It's also possible for the other xacro files to be loaded from other remote servers, then.

> And the import is working fine in typescript now.

What changed? Are you still planning to work on PR #78?

**Comment by joaopfg** [comment]
@gkjohnson I see, thanks! 

When I import the package locally I have no errors anymore, so I thought it was solved just by adding the tsconfig.json. Sorry, I'm a newbie in all this (typescript, packaging etc) . I begin working with it very recently for a task on my work :)

But when I run `npm run lint -- --fix` it seems there is nothing to fix. What do you think the issue can be ?

**Comment by gkjohnson** [comment]
You need to run `npm run lint` to see the issues. In the PR the CI runs you can see that what you have submitted fails to pass the lint check:

https://github.com/gkjohnson/xacro-parser/runs/5054933358?check_suite_focus=true

You at least need to make the changes I posted in the PR -- ie install typescript, remove the ts files from the eslint check
